### ISSUE TITLE
Wiener before CTF shows wrong Thon rings

### ISSUE THREAD

**Issue by scherers** [C-CINA/2dx#106]
When looking at the simulated Thon rings of the newly added CTF-before-Unbending option I observe this potential aliasing effect as discussed before. Now I processed an image with a high defocus and got the attached CTF in tiles. For me this looks like a bug as the somehow the simulated power-spectrum is 30% too small!? I had a look at the code doing the CTF-correction in tiles and I did not find APIX, which is required for CTF correction. We have a pixel size of 1.34A for the dataset. This could explain the 30% error we get by implicitly setting APIX=1 instead of 1.34. Does somebody agree?

![screenshot from 2014-12-08 16 01 54](https://cloud.githubusercontent.com/assets/591680/5341145/f44a6b48-7ef3-11e4-82ec-1357a53b0cc1.png)

**Comment by sthennin** [comment]
the new CTF correction in stripes now works with FFTW and correctly addresses reciprocal space.
