### ISSUE TITLE
2dx is "forgetting" map paramters 

### ISSUE THREAD

**Issue by markfrosenberg** [C-CINA/2dx#110]
For some inexplicable  reason 2dx is "forgetting" (only for certain images)  whether for example the map is flipped in "Generate Map".  One can initially select the flags but when the image is closed down and re-opened the flags resume their normal default values. I have tried selecting the flags in the .cfg file making sure they were inherited with the higher levels to no avail.

**Comment by sthennin** [comment]
This is caused by synchronisation with the upper-level config file in 2dx_merge, if the synchronisation is still active for that parameter.  This is to make sure the entire project has, e.g., only one definition of symmetry. It is supposed to be like that.
