### ISSUE TITLE
Linux - Libboost 1.53.0

### ISSUE THREAD

**Issue by mitochos** [C-CINA/2dx#114]
New versions of Linux (Debian and Ubuntu) don't support libboost 1.53.0 anymore. Libboost 1.54.0 and 1.55.0 are pre-installed and need to be replaced by the old version to get 2dx running (https://launchpad.net/ubuntu/saucy/amd64/libboost-system1.53-dev/1.53.0-6+exp3ubuntu8).

**Comment by sthennin** [comment]
Libboost is not required.
