### ISSUE TITLE
/INSTALL.SOURCE is outdated and should be removed. 

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#115]
/INSTALL.SOURCE describes compilation via ./configure; make; ...    which doesn't exist any longer.

**Comment by sthennin** [comment]
On OSX: 

FFTW: Download from 
http://www.fftw.org/download.html
Then install with:
./configure --enable-single --enable-fast-install
make
sudo make install

Qt requires version 4.x, not newer.
Currently, this can be found at:
http://download.qt.io/archive/qt/

MacPorts:
http://guide.macports.org/#installing

BOOST:
sudo port install cmake
sudo port install boost

SPIDER:
Download from:
http://spider.wadsworth.org/spider_doc/spider/docs/spi-download.html
Install via
sudo tar -C /usr/local -xvf spiderweb.22.03.tar

GCC and GFORTRAN:  
Download from:
http://hpc.sourceforge.net
Install via
sudo tar -xvf gcc-4.9-bin.tar -C /
sudo tar -xvf gfortran-4.9-bin.tar -C /

**Comment by sthennin** [comment]
I simply deleted INSTALL.SOURCE, and the ./build_all script crashed because it wasn't finding this file. So, it is currently still needed for compilation (explicitly copied somewhere?).

**Comment by nikhilbiyani** [comment]
Files are now cleaned, still kept the INSTALL.SOURCE file, as it might help the users to tell how to install via source. We must update it rather! Closing this issue!
