### ISSUE TITLE
Bugs in 2dx new version

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#120]
2dx_image:
- progress bar at the bottom of the main GUI is too tall and should not be able to grow.
- full-screen browser:  on FFT display: Button "c" doesn't work.  Console output: QPixmap::grabWidget is deprecated, use QWidget::grab() instead

- Console output during running:  
2dx_image[6949] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'

**Comment by nikhilbiyani** [comment]
Progress bar: fixed
button 'c' does work on Linux!

**Comment by nikhilbiyani** [comment]
All fixed
