### ISSUE TITLE
"image not found" error as going along

### ISSUE THREAD

**Issue by vinzenzunger** [C-CINA/2dx#122]
Hello,
just updated to 3.5.0 ....nice new look! 
All seems to go well until I try run the Defocus&Tilt Calculation. There is comes up with the following
################################2dx_getDefTilt################################
==== Using CTFTILT. ===================================================================================================
Using resolution range 80.0A ... 7A, and tiles of 128 pixels width.
==== 2dx_ctftilt - to get defocus and tilt. ===========================================================================
###########################2dx_getDefTilt finished.###########################
dyld: Library not loaded: /opt/2dx/kernel/mrc/lib/libquadmath.0.dylib 
Referenced from: /Applications/2dx/kernel/mrc/lib/libgfortran.3.dylib 
Reason: image not found 

Any suggestions
Best wishes
Vinzenz

**Comment by nikhilbiyani** [comment]
Hi. This is an issue with packaging. Can you please tell me more about your OS? Thanks.

**Comment by vinzenzunger** [comment]
The Macs running Yosemite (10.10.3 and 10.10.4). I "accidentally" found a work around ...I installed the previous/old 2dx version (stable release) and followed that by installation of the new version, and now it works just fine. Currently only scratching my head how to convert .dm4 movies to .mrc movies without loosing data, so that I could try the movie processing mode to see what difference that makes. So far, I haven't figured that part out, and the manuals are not yet flashed out to give good instructions how to deal with movie files.   Thanks for your help!

**Comment by nikhilbiyani** [comment]
So this should be done now! See below the otool -L command output:

Users/bs-hudson/jenkins/jenkins_builds/trunk_nb_inst/kernel/mrc/lib/libgfortran.3.dylib:
	/opt/local/lib/libgcc/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@executable_path/../lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@executable_path/../lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)


@vinzenzunger can you please delete all installed versions of 2dx and do a fresh installation using latest files in: http://www.2dx.unibas.ch/download/2dx-software/2dx-for-mac-.pkg

**Comment by vinzenzunger** [comment]
Hi Nihkil,
Thank you very much for looking into it. I will try it on our lab iMac when I get back from Thanksgiving break next week.
Have a great weekend
Best wishes
Vinzenz

Northwestern University
Dept of Molecular Biosciences
2205 Tech Dr
Hogan 2-100
Evanston, IL 60208

office: Silverman 4619
phone: (847) 467-2178
