### ISSUE TITLE
El Capitan version doesn't run on El Capitan

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#123]
Error:
dyld: Library not loaded: /usr/lib/system/libsystem_stats.dylib 
Referenced from: /Applications/2dx/kernel/mrc/lib/libSystem.B.dylib 
Reason: image not found

**Comment by nikhilbiyani** [comment]
There is no El Capitan version available.We are not yet distributing a package for OSX 10.11. I was waiting for resources and will soon come up with a package.

**Comment by sthennin** [comment]
Ok, we then have to compile it on El Capitan ourselves, which works.
