### ISSUE TITLE
Map / Reference preview still buggy

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#126]
The maps and also the references in 2dx_merge top right corner, when switching to automatic toggle, are not always the correct images as on the hard drive. Somehow, old maps from neighboring image directories are cached and displayed instead.  With the newly renumbered images, all reference map files are now created correctly, but this function still displays sometimes the wrong maps. Could there be a hidden cache somewhere?

**Comment by nikhilbiyani** [comment]
This will need a rewrite of the plugin!! I also suspect that the plugin takes some time to load the map and if the refresh time is smaller than that it shows the older map instead.

**Comment by sthennin** [comment]
... but when you don't have the toggle mode active, then everything works and is very fast. There, each time the active directory changes, the new map is displayed instantly. 
Could you have something that each time the active directory changes, all three maps are loaded into the memory of the toggle function?

**Comment by nikhilbiyani** [comment]
Yes, it is expected to do that! I will have to check the implementation of the plugin.
