### ISSUE TITLE
Refine switch does not apply changes to the images

### ISSUE THREAD

**Issue by rdrighetto** [C-CINA/2dx#127]
Whenever I run the "Refine Switch" custom script, it does run performing the tests specified (e.g. change revhk), but in the end it gives the following error:

########################2dx_DetermineSwitch finished.#########################
app_2dx_image: Undefined variable. 

I circumvent the problem by adding the following line to the beginning of script ./merge/SCRATCH/2dx_execute_merge_results.script:

set app_2dx_image = `which 2dx_image`

and then I source it from csh.

Then the script is able to call 2dx_image and apply the changes found.

But I think this should be done automatically by default.

**Comment by sthennin** [comment]
I added the line 
set app_2dx_image = ""
to all scripts in the top section. Will be submitted to GitHub later today.
