### ISSUE TITLE
FSC in 2dx

### ISSUE THREAD

**Issue by nikhilbiyani** [C-CINA/2dx#129]
After calculation of 3D final map we would like to get an estimate the of the resolution of the generated map. This is in "Single Particle Reconstruction" done using splitting the data into two halves: Even and Odd. Two separate maps are generated using the two data sets! A FSC curve can be then be plotted to guess an estimate using the 0.143 crossing. 

How to do this in 2dx?

Possible way would be automatically assign each image with even or odd map internally. When running the "Merge Once" or "Final Merge" script, we internally generate two different maps. I guess the "Refine Phase Origins" could still use reference from the full data.

**Comment by sthennin** [comment]
Yes, great idea.
We should in the Merge step create four volumes:  
1) All images, RESMAX limited.
2) All images, limited to MergeResolution
3) Even images, RESMAX limited.
4) Odd images, RESMAX limited.

We then use the FSC between 3) and 4) to estimate the resolution, then filter 2) to that resolution (e.g. using some radial MTF correction and also B-factor sharpening, and then multiplying the amplitudes radially with the FSC profile, to create the next reference for phase origin refinement. The final map 1) is produced with full RESMAX, but quality evaluated by the FSC curve. 

This, at least, would be the approach for noisy single particles.  However, I am not sure if this is also the right approach for 2D crystal images, where each processed APH file is already a kind of class-average that has very little noise and that has already FOM weights for every reflection.   These FOM weights should weigh down the highest-resolution spots. We don't need to resolution limit the reference too much here. I actually got better looking results when setting MergeResoluition to almost the same value as RESMAX.

**Comment by nikhilbiyani** [comment]
Selected images are now now also grouped as even and odd. One would need to make maps using these images and calculate the FSC.

**Comment by nikhilbiyani** [comment]
This one is done, @sthennin any more work to be done here?
