### ISSUE TITLE
Final Map orientation

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#132]
The final map made by 2dx_image and made by 2dx_merge (regenerate maps) are mirrored (left/right along the vertical axis) (or 180 degrees rotated ?)to each other. The final map from 2dx_merge right now agrees with the projected reference.

**Comment by nikhilbiyani** [comment]
The possible reason to this may be:

In 2dx_merge volume_processor.exe is used to create a map file from avrg.hkl while in 2dx_image we use ccp4 routines to generate the same. One of them must be wrong!

**Comment by sthennin** [comment]
We have an image that is a slightly distorted 2D crystal image with noise overlaid, and the unit cell is an image of an apple and it has text on each apple saying "This is an apple".  We need to process that image with 2dx, and see if the final map still has the text in the correct orientation.

**Comment by sthennin** [comment]
I checked with the APPL image. 2dx_merge is producing final maps that are 180deg rotated.  2dx_image is ok. This is now on the NAS, at /Volumes/cina/Projects/2dx/Apple .   Could you have a look, please?
