### ISSUE TITLE
When using SPIDER, 2dx expects /usr/local/spider/spider.exe, but no such file exists.

### ISSUE THREAD

**Issue by redplanks** [C-CINA/2dx#135]
Ubuntu 16.04, amd64 version. 2dx ver. 3.5.0, SPIDER ver. 23.02

A workaround is to symbolically link /usr/local/spider/bin/spider to /usr/local/spider/bin/spider.exe, by using "sudo ln -s /usr/local/spider/bin/spider /usr/local/spider/bin/spider.exe".

**Comment by nikhilbiyani** [comment]
Fixed with the current commit

**Comment by sthennin** [comment]
Spider is now completely removed.
