### ISSUE TITLE
Treat 3D .mrc files like .map files

### ISSUE THREAD

**Issue by rdrighetto** [C-CINA/2dx#137]
Open 3D maps in MRC format (the preferred format of FREALIGN and RELION) in Chimera 
(a workaround is to create a .map symlink for each 3D .mrc file, but this can become messy...)

**Comment by nikhilbiyani** [comment]
Implemented a workaround, now the file formats can be decided irrespective of the extension from the file name.

IMAGE MAP: image.mrc <IMAGE>

will load a the mrc image as MAP
