### ISSUE TITLE
Support for stacks/slices

### ISSUE THREAD

**Issue by rdrighetto** [C-CINA/2dx#138]
Display stacks of 2D images and slices of 3D volumes directly in the 2dx image viewer. This is important for single-particle tasks.

**Comment by sthennin** [comment]
We should in general always name MRC stacks with *.mrcs, and MRC files with *.mrc

**Comment by nikhilbiyani** [comment]
We can introduce a .mrcs translator, which will translate the .mrcs file and open it with e2display?

**Comment by sthennin** [comment]
mrcs translator is a good idea.

**Comment by rdrighetto** [comment]
Implemented earlier today.
