### ISSUE TITLE
Thon ring display in full-screen version of full-screen browser not working

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#144]
When displaying an FFT, and going into full-screen mode (CMD-F), and then displaying Thonrings with "C", then the map disappears and only the dialogue remains.

**Comment by nikhilbiyani** [comment]
It works, with new macOS (10.9 +) the fullscreen are on different desktops. You can only see that full screened thing on that desktop, anything else would go on the default screen.

**Comment by sthennin** [comment]
Nope, sorry, doesn't work. Try yourself, on OS X 10.10 or 10.11:
open FFT by double-clicking
CMD-f
c
c
c
c

**Comment by sthennin** [comment]
BTW, same problem occurs when using only one screen, or when using two screens.

**Comment by nikhilbiyani** [comment]
Yes, its on other desktop, on mac book after you press c, press gather windows button over f3. On the top you will notice a bar and there different desktops. The second desktop will be of the full screen browser

**Comment by nikhilbiyani** [comment]
It is how it is with macOS!
