### ISSUE TITLE
Gain Reference

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#147]
We need also to be able to import the Gain Reference in the IMPORT IMAGES window:
After "Subdirectory containing raw stack", we need "Gain reference file".
This should also be copied into the newly imported directory, but not be renamed. It should keep its original name, which could be something like "CountRef_TssA_Sep28_15.27.14.dm4".
This name should be given to the newly created 2dx_image.cfg under the parameter name "import_gainref".

**Comment by sthennin** [comment]
Currently, the script "Unpack Stack" has a temporary fix to copy the gain reference explicitly. This has to be removed later.

**Comment by nikhilbiyani** [comment]
Done, implemented!
