### ISSUE TITLE
Library: Preview of Image/FFT/Final Map should be smoothed with Qt::IgnoreAspectRatio, Qt::SmoothTransformation

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#151]
Could this still be implemented also in the "Library" preview?

Such as:
pixmap = sourceImage->getPixmap().scaled((int) (scale * image->width()), (int) (scale * image->height()), Qt::IgnoreAspectRatio, Qt::SmoothTransformation);

**Comment by sthennin** [comment]
Also, we calculate a 400x400 px preview into every MRC file, by adding that together with a second copy of the header to the end of the MRC file. When calculating this within 2dx, we should probably apply smoothing also, to increase the SNR.  Smoothing should ideally be done with a Lanczos filter in real space, which is the same (?) as a Butterworth filter in Fourier space.

**Comment by nikhilbiyani** [comment]
Done, now with PNG
