### ISSUE TITLE
image preview in Library.cpp panel appears skewed for non-square images

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#153]
It might also be nice to see the image and its FFT on the same time.
Also, the image should be two times larger than currently shown in the Library.cpp panel.

**Comment by sthennin** [comment]
This now works with the MRC files, which is a bit slow.  We already planed to move to PNG files with the same name.mrc.png. 
Currently, the preview images are 200x200px in size. Could there be an option to make these become 400x400 instead?  On the large screen at the microscope, that would be super useful.  When processing images on a portable laptop instead, then the 200x200 is ok.    (Sorry to bother you with this).

**Comment by nikhilbiyani** [comment]
Fixed in the latest commit!
