### ISSUE TITLE
import cue stalling

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#158]
Still the same bug:
Once the import cue is empty, it stops.
It will not Rescan the import Folder, even if there are more images recorded on the Titan, and all switches are set to on.

**Comment by sthennin** [comment]
I think this is happening:
The import cue loads all images from the K2 until the disk on the K2 computer only contains the last two images that were recorded within the last 180seconds. 
Because the import cue is then finished with all ready-to-import images, and because on the same time the cue is not empty, it is not checking for more images and doesn't even check if the two last images in the cue are now old enough. There it stays indefinitely. 

Could that be?

**Comment by nikhilbiyani** [comment]
It works now!
