### ISSUE TITLE
tilt axis in final map (shift-T) doesn't rotate correctly upon Rot90 and Rot180

### ISSUE THREAD

**Issue by scherers** [C-CINA/2dx#21]
tilt axis in final map (shift-T) doesn't rotate correctly upon Rot90 and Rot180

**Comment by sthennin** [comment]
True. Would require programming in 2dx_image full-screen browser.  The alternative is to not use ROT90 etc., but to re-index the image lattice, and reprocess it all.  
ROT90 etc refinements work well, however, just the display is wrong.
