### ISSUE TITLE
Results window interpretation requires ""

### ISSUE THREAD

**Issue by scherers** [C-CINA/2dx#29]
If I try to set a variable to a certain value with a Custom-1.script, then the parameter requires "".
echo "set SYN_Unbending = 1" >> LOGS/${scriptname}.results
does not do it.

But 
echo "set SYN_Unbending = \"1\"" >> LOGS/${scriptname}.results

doesn't work either, because csh is filtering out the \".

How can we echo " into a results file?
Or, can we modify the results interpreter of 2dx_merge, so that parameters without the " can also be interpreted?

**Comment by sthennin** [comment]
Works.
