### ISSUE TITLE
Refine Spotlist doesn't work

### ISSUE THREAD

**Issue by scherers** [C-CINA/2dx#7]
Added by Henning Stahlberg on Aug 26, 2012 02:23 PM
It works, but the problem is actually now elsewhere:
The automatic lattice identification can find two different first and second lattices, which actually are exactly the same ones. Spotlist exclusion then will remove ALL spots, leaving 0 spots.
   
Added by Sebastian Scherer on Aug 26, 2012 04:53 PM
Could be solved by subtracting the first and second lattice spots and if the result is zero (or almost) there is only one lattice.

The other way would be to program a symmetry dependent if statement which checks all possibilities. I would prefer the first fix. ;)

**Comment by sthennin** [comment]
didn't show up as a problem lately.
